name: McRPG
version: 1.3
author: Condolent
main: me.condolent.McRPG
commands:
   rpg:
      description: Base command for McRPG
   w:
      description: Sends a whisper to a player
   y:
      description: Sends out a server-wide yell.
   supply:
      description: Supply a player with an item.
   heal:
      description: Heal a specified online player to full health.
   class:
      description: Choose which class you'd like to play as.
   ci:
      description: Clears your inventory from EVERYTHING. (Cannot undo)
   gm:
      description: Changes your gamemode. 0/1/survival/creative
   setspawn:
      description: Sets server-spawn.
   spawn:
      description: Teleports the player to spawn.
   faction:
      description: Choose your faction.
   balance:
      description: Shows your current balance.
   vanish:
      description: Makes you invisible for 2 minutes.
   sell:
      description: Sell the item in your hand!
   achievement:
      description: Show a list of achievements.
   admin:
      description: Opens up a admin menu.

permissions:
   mcrpg.admin:
      description: Default admin privileges.